### ISSUE TITLE
Unable to run examples

### ISSUE THREAD

**Issue by hrwaik** [kblin/ncbi-acc-download#10]
Hi,

Just installed ncbi-acc-download using pip and trying to run a quick example to make sure it works however when I run this I get this error (This happens when I also just run ncbi-acc-download --help).

Traceback (most recent call last):
  File "/home/huw/anaconda2/bin/ncbi-acc-download", line 6, in <module>
    from ncbi_acc_download.__main__ import main
  File "/home/huw/anaconda2/lib/python2.7/site-packages/ncbi_acc_download/__main__.py", line 6, in <module>
    from .core import download_to_file, generate_url, Config, HAVE_BIOPYTHON
  File "/home/huw/anaconda2/lib/python2.7/site-packages/ncbi_acc_download/core.py", line 24, in <module>
    from ncbi_acc_download.download import (
  File "/home/huw/anaconda2/lib/python2.7/site-packages/ncbi_acc_download/download.py", line 83
    print("Failed to download {!r} from NCBI".format(params['id']), file=sys.stderr)
                                                                        ^
SyntaxError: invalid syntax

I have installed ncbi-genome-download using the same method and have no problem with that where it runs for whatever I try. Does anyone know what might have happened here?

Thanks

**Comment by kblin** [comment]
Ah, my bad, I forgot to test this with Python 2.7. I'll have a fix for this soonish, but considering Python 2 will be retired in about 8 months (https://pythonclock.org/), maybe you want to run `ncbi-acc-download` in Python 3 instead?

**Comment by kblin** [comment]
Should be fixed in the 0.2.5 release.
