### ISSUE TITLE
Can't download gff3 files when running in --recursive mode.

### ISSUE THREAD

**Issue by ewilbanks** [kblin/ncbi-acc-download#24]
Hi folks,

Thanks so much for this awesome tool.  LOVE IT.  I'm having the following issue when trying to recursively download GFF3 files from a WGS record.

```
$ ncbi-acc-download --recursive ALVJ00000000.1 -F gff3 -o ALVJ00000000.1.gff
Traceback (most recent call last):
  File "/opt/miniconda3/bin/ncbi-acc-download", line 10, in <module>
    sys.exit(main())
  File "/opt/miniconda3/lib/python3.9/site-packages/ncbi_acc_download/__main__.py", line 66, in main
    download_to_file(dl_id, config, filename, append)
  File "/opt/miniconda3/lib/python3.9/site-packages/ncbi_acc_download/core.py", line 131, in download_to_file
    _validate_and_write(r, fh, dl_id, config)
  File "/opt/miniconda3/lib/python3.9/site-packages/ncbi_acc_download/core.py", line 175, in _validate_and_write
    downloaded = download_wgs_parts(handle, config)
  File "/opt/miniconda3/lib/python3.9/site-packages/ncbi_acc_download/wgs.py", line 102, in download_wgs_parts
    records = list(SeqIO.parse(handle, config.format))
  File "/opt/miniconda3/lib/python3.9/site-packages/Bio/SeqIO/__init__.py", line 609, in parse
    raise ValueError("Unknown format '%s'" % format)
ValueError: Unknown format 'gff3'
```

I can download the genbank and fasta files recursively for this entry without an issue.  I can also download the gff3 files for an individual accession under this WGG entry.  For example, the following worked just fine.

`ncbi-acc-download ALVJ01000001.1 -F gff3 -o ALVJ00000000.1.gff`

Thoughts on how to trouble shoot this?

Thanks!
Lizzy

**Comment by kblin** [comment]
Hi there, sorry that I missed this issue initially.
`ncbi-acc-download` relies on Biopython to handle validation and looking up which sequences to download in a recursive download. Biopython doesn't support gff, which is why you get this error. I don't see a good way of fixing this without switching to another sequence parsing library, and I don't really see a good option for that at the moment.

On a side note, `--recursive` won't do anything in FASTA files, I don't even think you can get WGS master records in FASTA format. Recursive mode really only does something for GenBank files.
