### ISSUE TITLE
Connection broken

### ISSUE THREAD

**Issue by shimingt** [kblin/ncbi-acc-download#9]
Hello there,

I am trying to download Genbank for multiple accession IDs(~ 20,000). Unfortunately, the connection broke in the middle of downloading, and I came across this error message:

AD01000005.1' aborted: ('Connection broken: OSError("(104, \'ECONNRESET\')")', OSError("(104, 'ECONNRESET')"))
Traceback (most recent call last):
  File "/home/tanshiming/anaconda3/lib/python3.7/site-packages/urllib3/contrib/pyopenssl.py", line 294, in recv_into
    return self.connection.recv_into(*args, **kwargs)
  File "/home/tanshiming/anaconda3/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1814, in recv_into
    self._raise_ssl_error(self._ssl, result)
  File "/home/tanshiming/anaconda3/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1631, in _raise_ssl_error
    raise SysCallError(errno, errorcode.get(errno))
OpenSSL.SSL.SysCallError: (104, 'ECONNRESET')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tanshiming/anaconda3/lib/python3.7/site-packages/urllib3/response.py", line 360, in _error_catcher
    yield
  File "/home/tanshiming/anaconda3/lib/python3.7/site-packages/urllib3/response.py", line 669, in read_chunked
    chunk = self._handle_chunk(amt)
  File "/home/tanshiming/anaconda3/lib/python3.7/site-packages/urllib3/response.py", line 624, in _handle_chunk
    returned_chunk = self._fp._safe_read(self.chunk_left)
  File "/home/tanshiming/anaconda3/lib/python3.7/http/client.py", line 610, in _safe_read
    chunk = self.fp.read(min(amt, MAXAMOUNT))
  File "/home/tanshiming/anaconda3/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/home/tanshiming/anaconda3/lib/python3.7/site-packages/urllib3/contrib/pyopenssl.py", line 299, in recv_into
    raise SocketError(str(e))
OSError: (104, 'ECONNRESET')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tanshiming/anaconda3/lib/python3.7/site-packages/requests/models.py", line 750, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/home/tanshiming/anaconda3/lib/python3.7/site-packages/urllib3/response.py", line 490, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/home/tanshiming/anaconda3/lib/python3.7/site-packages/urllib3/response.py", line 694, in read_chunked
    self._original_response.close()
  File "/home/tanshiming/anaconda3/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/tanshiming/anaconda3/lib/python3.7/site-packages/urllib3/response.py", line 378, in _error_catcher
    raise ProtocolError('Connection broken: %r' % e, e)
urllib3.exceptions.ProtocolError: ('Connection broken: OSError("(104, \'ECONNRESET\')")', OSError("(104, 'ECONNRESET')"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tanshiming/anaconda3/lib/python3.7/site-packages/ncbi_acc_download/download.py", line 97, in write_stream
    for chunk in request.iter_content(4096, decode_unicode=True):
  File "/home/tanshiming/anaconda3/lib/python3.7/site-packages/requests/utils.py", line 505, in stream_decode_response_unicode
    for chunk in iterator:
  File "/home/tanshiming/anaconda3/lib/python3.7/site-packages/requests/models.py", line 753, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ('Connection broken: OSError("(104, \'ECONNRESET\')")', OSError("(104, 'ECONNRESET')"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tanshiming/anaconda3/bin/ncbi-acc-download", line 11, in <module>
    sys.exit(main())
  File "/home/tanshiming/anaconda3/lib/python3.7/site-packages/ncbi_acc_download/__main__.py", line 54, in main
    download_to_file(dl_id, config, filename, append)
  File "/home/tanshiming/anaconda3/lib/python3.7/site-packages/ncbi_acc_download/core.py", line 118, in download_to_file
    _validate_and_write(r, fh, dl_id, config)
  File "/home/tanshiming/anaconda3/lib/python3.7/site-packages/ncbi_acc_download/core.py", line 159, in _validate_and_write
    write_stream(request, handle, dl_id, config)
  File "/home/tanshiming/anaconda3/lib/python3.7/site-packages/ncbi_acc_download/download.py", line 107, in write_stream
    raise DownloadError(str(err))
ncbi_acc_download.errors.DownloadError: ('Connection broken: OSError("(104, \'ECONNRESET\')")', OSError("(104, 'ECONNRESET')"))

Could someone please kindly help/advice?

Thanks!

**Comment by tseemann** [comment]
@shimingt what *exact* command did you run to download 20,000 accessions?
